name: Build the Docker Container

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: talusbio/bioconda-tools

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        tags: ${{ env.IMAGE_NAME }}:test

    - name: Test the Docker image
      run: docker run --rm ${IMAGE_NAME}:test comet -p

    - name: Log in to the GitHub Container Registry
      if: ${{ github.event_name == 'release' }}
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      if: ${{ github.event_name == 'release' }}
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    # Note that the image is cached from the test build, so it won't be build a
    # second time. Correspondingly, this step only pushes it to the GitHub
    # Container Registry.
    - name: Push the Docker image to the GHCR
      uses: docker/build-push-action@v2
      if : ${{ github.event_name == 'release' }}
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
